### ISSUE TITLE
Installation instructions ?

### ISSUE THREAD

**Issue by an99990** [Serafadam/depthai_ros_driver#27]
Hi,
great repo. Is it possible to have some instructions on how to install your project outside vscode.
Like command lines, i cant just colcon build depthai_ros_driver. it doesnt seem to work ..
thank you

**Comment by Serafadam** [comment]
Hey, because this is using shared libraries, colcon commands get a little bit more complicated, you can either run `build_workspace.sh` script (or take a look inside to see the build commands`, or use simple command to set up the whole workspace in one command (I've added it in https://github.com/Serafadam/depthai_ros_driver/pull/28), see the current readme.
